name: DevOps with GCP

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Authenticate with GCP using GitHub secrets (no need for a file reference)
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'  # Ensure this secret contains the full JSON key

      # Step 2: Set up the Cloud SDK
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      # Step 3: Checkout code (if needed for context)
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      # Step 4: Configure Docker to use GCP registry
      - name: 'Configure Docker with gcloud'
        run: |
          gcloud auth configure-docker

      # Step 5: Build and Push Docker Image
      - name: 'Build and Push Docker Image'
        run: |
          gcloud builds submit --tag us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/github1:latest .
