name: DevOps with GCP

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4
      
    - name: 'gcloud auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: |
        gcloud auth configure-docker
        gcloud builds submit --tag us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/github1/flask_gcp:latest .
  helm:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 'Upload Helm charts'
      uses: 'azure/setup-helm@v4'
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: 'gcloud auth2'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: 'fetching access token'
      run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev --quiet
          export ACCESS_TOKEN=$(gcloud auth print-access-token)
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV  # Persisting ACCESS_TOKEN to environment for next steps
    - name: 'running helm commands'
      run: |
        helm package helm-oci
        echo '${{ env.ACCESS_TOKEN }}' | helm registry login -u oauth2accesstoken --password-stdin https://us-east1-docker.pkg.dev
        helm push my-api-chart-0.1.0.tgz oci://us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/github1/helm-chart1
        
  deploy: 
   needs: [build, helm]
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
    - name: 'Upload Helm charts'
      uses: 'azure/setup-helm@v4'
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: 'gcloud auth3'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: 'provisioning cluster'
      run: |
       gcloud container clusters describe --zone us-east1 chart-cluster || \
       gcloud container clusters create --zone us-east1 chart-cluster --disk-size 50GB --num-nodes=2 --enable-ip-alias --node-machine-type n1-standard-2 --address ""
       gcloud container clusters get-credentials --zone us-east1 chart-cluster
    - name: 'Deploying app'
      run: |
        echo '${{ env.ACCESS_TOKEN }}' | helm registry login -u oauth2accesstoken --password-stdin https://us-east1-docker.pkg.dev
        helm upgrade --install helm-oci oci://us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/github1/helm-chart1/my-api-chart
