name: DevOps with GCP

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4
      
    - name: 'gcloud auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: |
        gcloud auth configure-docker
        gcloud builds submit --tag us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/github1/flask_gcp:latest .
  helm:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 'Upload Helm charts'
      uses: 'azure/setup-helm@v4'
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: 'running helm commands'
      run: |
        helm package helm-oci -d . -o helm-oci-0.1.0.tgz
        helm registry login -u oauth2accesstoken --password string '${{ secrets.GCP_CREDENTIALS }}' https:///us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/github1
        helm push helm-oci-0.1.0.tgz oci://us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/github1/helm-chart1
