name: DevOps with GCP

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      uses: actions/checkout@v4
      with:
        sparse-checkout: Dockerfile
        run: |
          gcloud auth configure-docker
          gcloud builds submit --tag us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/github1:latest .
